plugins {
    id 'java-library'
}

group 'org.mentalizr'
version '1.0-SNAPSHOT'

repositories {
    mavenCentral()
    maven { url "https://raw.githubusercontent.com/arthurpicht/mvn-repo/main/releases"}
}

dependencies {
    implementation libs.m7r.commons
    implementation libs.m7r.serviceObjects

    implementation libs.qos.logback

    implementation libs.ap.utils.core
    implementation libs.ap.configuration

    testImplementation libs.ap.utils.io
    testImplementation libs.junit.jupiter
    testRuntimeOnly libs.junit.engine
}

test {
    useJUnitPlatform()
}

